require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommonFeastsController do

  # This should return the minimal set of attributes required to create a valid
  # CommonFeast. As you add validations to CommonFeast, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommonFeastsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all common_feasts as @common_feasts" do
      common_feast = CommonFeast.create! valid_attributes
      get :index, {}, valid_session
      assigns(:common_feasts).should eq([common_feast])
    end
  end

  describe "GET show" do
    it "assigns the requested common_feast as @common_feast" do
      common_feast = CommonFeast.create! valid_attributes
      get :show, {:id => common_feast.to_param}, valid_session
      assigns(:common_feast).should eq(common_feast)
    end
  end

  describe "GET new" do
    it "assigns a new common_feast as @common_feast" do
      get :new, {}, valid_session
      assigns(:common_feast).should be_a_new(CommonFeast)
    end
  end

  describe "GET edit" do
    it "assigns the requested common_feast as @common_feast" do
      common_feast = CommonFeast.create! valid_attributes
      get :edit, {:id => common_feast.to_param}, valid_session
      assigns(:common_feast).should eq(common_feast)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommonFeast" do
        expect {
          post :create, {:common_feast => valid_attributes}, valid_session
        }.to change(CommonFeast, :count).by(1)
      end

      it "assigns a newly created common_feast as @common_feast" do
        post :create, {:common_feast => valid_attributes}, valid_session
        assigns(:common_feast).should be_a(CommonFeast)
        assigns(:common_feast).should be_persisted
      end

      it "redirects to the created common_feast" do
        post :create, {:common_feast => valid_attributes}, valid_session
        response.should redirect_to(CommonFeast.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved common_feast as @common_feast" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommonFeast.any_instance.stub(:save).and_return(false)
        post :create, {:common_feast => {}}, valid_session
        assigns(:common_feast).should be_a_new(CommonFeast)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommonFeast.any_instance.stub(:save).and_return(false)
        post :create, {:common_feast => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested common_feast" do
        common_feast = CommonFeast.create! valid_attributes
        # Assuming there are no other common_feasts in the database, this
        # specifies that the CommonFeast created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommonFeast.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => common_feast.to_param, :common_feast => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested common_feast as @common_feast" do
        common_feast = CommonFeast.create! valid_attributes
        put :update, {:id => common_feast.to_param, :common_feast => valid_attributes}, valid_session
        assigns(:common_feast).should eq(common_feast)
      end

      it "redirects to the common_feast" do
        common_feast = CommonFeast.create! valid_attributes
        put :update, {:id => common_feast.to_param, :common_feast => valid_attributes}, valid_session
        response.should redirect_to(common_feast)
      end
    end

    describe "with invalid params" do
      it "assigns the common_feast as @common_feast" do
        common_feast = CommonFeast.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommonFeast.any_instance.stub(:save).and_return(false)
        put :update, {:id => common_feast.to_param, :common_feast => {}}, valid_session
        assigns(:common_feast).should eq(common_feast)
      end

      it "re-renders the 'edit' template" do
        common_feast = CommonFeast.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommonFeast.any_instance.stub(:save).and_return(false)
        put :update, {:id => common_feast.to_param, :common_feast => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested common_feast" do
      common_feast = CommonFeast.create! valid_attributes
      expect {
        delete :destroy, {:id => common_feast.to_param}, valid_session
      }.to change(CommonFeast, :count).by(-1)
    end

    it "redirects to the common_feasts list" do
      common_feast = CommonFeast.create! valid_attributes
      delete :destroy, {:id => common_feast.to_param}, valid_session
      response.should redirect_to(common_feasts_url)
    end
  end

end
